# Generated by Django 5.2.5 on 2025-08-23 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='RUNNING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('reference_utc', models.DateTimeField(blank=True, null=True)),
                ('csv_path', models.CharField(blank=True, max_length=512, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StoreTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone_str', models.CharField(default='America/Chicago', max_length=64)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tz', to='monitor.store')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime_last_hour_m', models.IntegerField()),
                ('uptime_last_day_h', models.FloatField()),
                ('uptime_last_week_h', models.FloatField()),
                ('downtime_last_hour_m', models.IntegerField()),
                ('downtime_last_day_h', models.FloatField()),
                ('downtime_last_week_h', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='monitor.report')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.store')),
            ],
            options={
                'indexes': [models.Index(fields=['report', 'store'], name='monitor_rep_report__53ae14_idx')],
                'unique_together': {('report', 'store')},
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(db_index=True)),
                ('start_time_local', models.TimeField()),
                ('end_time_local', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bizhours', to='monitor.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'day_of_week'], name='monitor_bus_store_i_db9c67_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_utc', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=16)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='monitor.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'timestamp_utc'], name='monitor_sto_store_i_901532_idx')],
            },
        ),
    ]
